# Generated by Django 2.2.1 on 2019-05-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eat_date', models.DateField(verbose_name='Date Eaten')),
                ('total_calories', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_text', models.CharField(max_length=200)),
                ('calories', models.IntegerField(default=0)),
                ('foodlist', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='foodlog.Foodlist')),
            ],
        ),
    ]
